# -*- coding: utf-8 -*-
"""stegography (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ix3dXlWrDEJNxyzc9gufL5xbFrlzr_mJ
"""

# -*- coding: utf-8 -*-
"""steganography_u_net13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FsmHJCAY_19zAUqB5kedYFfoCnzVQ0R7
"""

# -*- coding: utf-8 -*-
"""Optimized Steganography Model - Fast Training Version"""
# 1. Install required packages
!pip install opencv-python scikit-image tensorflow-addons
!pip install --upgrade tensorflow

# 2. Imports
import os
import numpy as np
import cv2
from tensorflow.keras import layers, Model, optimizers, callbacks
from tensorflow.keras.applications import VGG19
import tensorflow as tf
from tqdm import tqdm

# Enable mixed precision
from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy('mixed_float16')
print('Mixed precision enabled')

# 3. GPU Configuration
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        print(e)

# 4. Data Paths
trainpath = '/kaggle/input/dataframe/data frame/train'
valpath = '/kaggle/input/dataframe/data frame/val'
testpath = '/kaggle/input/dataframe/data frame/test'

# Image size
s = 64

# 5. Global VGG Feature Extractor
vgg = VGG19(include_top=False, weights='imagenet', input_shape=(s, s, 3))
feat_extractor = Model(vgg.input, vgg.get_layer('block3_conv3').output)

# 6. Image Processing
def process_image(image):
    """CLAHE-enhanced preprocessing"""
    image = cv2.resize(image, (s, s))
    lab = cv2.cvtColor(image, cv2.COLOR_BGR2LAB)
    l_channel, a_channel, b_channel = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    l_channel_clahe = clahe.apply(l_channel)
    lab_clahe = cv2.merge((l_channel_clahe, a_channel, b_channel))
    enhanced_img = cv2.cvtColor(lab_clahe, cv2.COLOR_LAB2BGR)
    return enhanced_img.astype(np.float32) / 255.0

# 7. Dataset Loader with Caching
def load_and_cache_data(path, cache_file):
    """Load and cache processed images as numpy arrays"""
    if os.path.exists(cache_file):
        data = np.load(cache_file)
        return data

    images = []
    print(f"Processing {path}...")
    for folder in tqdm(os.listdir(path)):
        folder_path = os.path.join(path, folder)
        if not os.path.isdir(folder_path):
            continue
        files = os.listdir(folder_path)
        for file in files[:1000]:  # Limit to 1000 images per class
            try:
                img = cv2.imread(os.path.join(folder_path, file))
                if img is not None:
                    images.append(process_image(img))
            except Exception as e:
                print(f"Error processing {file}: {str(e)}")

    images = np.array(images)
    np.save(cache_file, images)
    return images

# 8. Load Data
def load_dataset():
    X_train = load_and_cache_data(trainpath, "train_cache.npy")
    X_val = load_and_cache_data(valpath, "val_cache.npy")
    X_test = load_and_cache_data(testpath, "test_cache.npy")
    return X_train, X_val, X_test

# 9. Encoder with proper input shape
def make_encoder(input_shape):
    inputs = layers.Input(shape=input_shape)
    x = layers.Conv2D(64, 3, padding='same', activation='relu')(inputs)
    x = layers.MaxPooling2D(2)(x)  # Reduces to 32x32
    x = layers.Conv2D(128, 3, padding='same', activation='relu')(x)
    return Model(inputs, x)

# 10. Decoder with proper shape handling
def make_decoder(input_shape):
    inputs = layers.Input(shape=input_shape)
    x = layers.Conv2DTranspose(128, 3, padding='same', activation='relu')(inputs)
    x = layers.UpSampling2D(2)(x)  # Upsamples to 64x64
    x = layers.Conv2D(64, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(3, 1, padding='same', activation='sigmoid')(x)
    return Model(inputs, x)

# 11. Revised Loss Functions
def perceptual_loss(y_true, y_pred):
    """Modified to handle the stego output shape (32x32x128)"""
    # Resize y_pred to match VGG input (64x64x3)
    y_pred_resized = tf.image.resize(y_pred, [64, 64])  # Resize to 64x64
    y_pred_3channel = y_pred_resized[..., :3]  # Take first 3 channels

    y_true = tf.cast(y_true, tf.float32)
    y_pred_3channel = tf.cast(y_pred_3channel, tf.float32)

    true_feat = feat_extractor(y_true)
    pred_feat = feat_extractor(y_pred_3channel)
    return tf.reduce_mean((true_feat - pred_feat)**2)

def rev_loss(s_true, s_pred):
    """Reconstruction loss remains unchanged"""
    return 0.7 * tf.reduce_mean(tf.square(s_true - s_pred)) + 0.3 * (1 - tf.reduce_mean(tf.image.ssim(s_true, s_pred, max_val=1.0)))

# [Rest of the code remains the same]

# 12. Build Model with proper shape handling

# 12. Build Model with Proper Output Handling
def build_model(input_shape):
    # Inputs
    secret = layers.Input(shape=input_shape, name='secret_input')
    cover = layers.Input(shape=input_shape, name='cover_input')

    # Encoder
    encoder = make_encoder((s, s, 6))  # 6 channels input
    stego = encoder(layers.Concatenate()([secret, cover]))

    # Intermediate processing to get 64x64x3 for perceptual loss
    stego_for_loss = layers.Conv2D(3, 1, padding='same')(stego)
    stego_for_loss = layers.UpSampling2D(2)(stego_for_loss)  # 32x32 -> 64x64

    # Decoder
    decoder = make_decoder(stego.shape[1:])
    recovered_s = decoder(stego)

    # Combined model
    model = Model(
        inputs=[secret, cover],
        outputs=[stego_for_loss, recovered_s],  # Now both outputs are 64x64x3
        name='steganography_model'
    )

    model.output_names = ['stego_output', 'recovered_secret_output']

    # Compile
    # Compile
    model.compile(
        optimizer=optimizers.Adam(1e-4),
        loss={
            'stego_output': perceptual_loss,
            'recovered_secret_output': rev_loss
        },
        metrics={
            'stego_output': ['accuracy', calculate_psnr],
            'recovered_secret_output': ['accuracy', calculate_psnr]
        }
)
    return model

from tensorflow.image import psnr

def calculate_psnr(y_true, y_pred):
    """Calculate PSNR between true and predicted images"""
    return psnr(y_true, y_pred, max_val=1.0)

# 13. Main Execution
if __name__ == "__main__":
    # Load data
    print("Loading dataset...")
    X_train, X_val, X_test = load_dataset()

    # Ensure equal splits and convert to numpy arrays
    half_train = len(X_train) // 2
    input_S = np.array(X_train[:half_train])
    input_C = np.array(X_train[half_train:half_train*2])  # Ensure equal size

    half_val = len(X_val) // 2
    input_SV = np.array(X_val[:half_val])
    input_CV = np.array(X_val[half_val:half_val*2])

    # Verify shapes
    print(f"\nTraining shapes - Secret: {input_S.shape}, Cover: {input_C.shape}")
    print(f"Validation shapes - Secret: {input_SV.shape}, Cover: {input_CV.shape}")

    # Build model
    print("\nBuilding model...")
    model = build_model((s, s, 3))
    model.summary()

    # Callbacks
    callbacks_list = [
        callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3),
        callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
    ]

    # Train
    print("\nStarting training...")
    history = model.fit(
        [input_S, input_C],
        {'stego_output': input_C, 'recovered_secret_output': input_S},
        validation_data=(
            [input_SV, input_CV],
            {'stego_output': input_CV, 'recovered_secret_output': input_SV}
        ),
        batch_size=32,
        epochs=11,
        callbacks=callbacks_list
    )

    # Plot results
    import matplotlib.pyplot as plt
    plt.figure(figsize=(12, 5))
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Val Loss')
    plt.title('Training History')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.show()

    # After training, add this code to evaluate on test set
    half_test = len(X_test) // 2
    input_ST = np.array(X_test[:half_test])
    input_CT = np.array(X_test[half_test:half_test*2])

    test_results = model.evaluate(
    [input_ST, input_CT],
    {'stego_output': input_CT, 'recovered_secret_output': input_ST},
    batch_size=32
    )

# Print PSNR results
    print("\nTest Results:")
    print(f"Stego PSNR: {test_results[3]:.2f} dB")  # Index 3 is stego_output PSNR
    print(f"Recovered Secret PSNR: {test_results[4]:.2f} dB")  # Index 4 is recovered_secret_output PSNR